#!/bin/bash

#
# Timeshift player script
# Usage:
# tvshift "mplayer dvb://channel"
#

TVCACHE=${TVCACHE:-~/tscache/}
TVPLAYER=${TVPLAYER:-"mplayer -profile dvb"}

bash -i -c "$1 -dumpstream -dumpfile /dev/fd/3 3>&1 1>/dev/null" | timeshift -d "$TVCACHE" | $TVPLAYER -
